### ISSUE TITLE
Directly use your pretrained checkpoint (mr=0.0) but get results much lower than the paper

### ISSUE THREAD

**Issue by xXuHaiyang** [mdswyz/IMDer#2]
Hi, thanks for your open-source work! 

I've modified the code and tried to test the performance on MOSI with your pretrained IMDer model (missing rate = 0.0), but I got results as follows: '64.7 / 64.0 / 24.4'. And it is much lower than the result shown in the paper: '85.7 / 85.6 / 45.3'. 

I wonder if there is something going wrong? I followed all your instructions (pretrained model, dataset, etc), and I use RTX 3090. My main packages are as follows, which I don't think should result in such big performance gap. 
<img width="665" alt="image" src="https://github.com/mdswyz/IMDer/assets/77454392/ce7152ed-0c6c-45af-a929-df6a51ed101f">

Could you please give me some advice on possible solutions?

**Comment by xXuHaiyang** [comment]
OK, maybe mr=0.0 should also be take into consideration in all the following missing strategy settings: https://github.com/mdswyz/IMDer/blob/1901a92f0c91017ef9ac0dc2f2ca0b101a4dec9c/trains/singleTask/IMDER.py#L64 https://github.com/mdswyz/IMDer/blob/1901a92f0c91017ef9ac0dc2f2ca0b101a4dec9c/trains/singleTask/IMDER.py#L65 

Otherwise `miss_2[int(self.args.mr*10-1)]` will be -1, which is the last element in the list.

**Comment by HKstetman** [comment]
I can't even use his pre-trained models. Returned with this:
![截屏2024-03-15 19 01 37](https://github.com/mdswyz/IMDer/assets/105272933/facc7644-f457-4dc6-ae6f-693a90df358d)

**Comment by xXuHaiyang** [comment]
> I can't even use his pre-trained models. Returned with this: ![截屏2024-03-15 19 01 37](https://private-user-images.githubusercontent.com/105272933/313166593-facc7644-f457-4dc6-ae6f-693a90df358d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2OTUzMjQsIm5iZiI6MTcxMDY5NTAyNCwicGF0aCI6Ii8xMDUyNzI5MzMvMzEzMTY2NTkzLWZhY2M3NjQ0LWY0NTctNGRjNi1hZTZmLTY5M2E5MGRmMzU4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxN1QxNzAzNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZGE0OGQwOGM1MDM4MmQyNjVmMDUyMDczY2UwNDRjNzM0MTZhOWUzYmNjNTIxOGNiZTliZDkxNzcyYzI0MTQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pjhoEvzDrYrTwrXHm5cNQxfBly8gztCLrThH17ytW_Q)

Hi, maybe you should check your package 'transformers' be 4.28.0. 
<img width="547" alt="image" src="https://github.com/mdswyz/IMDer/assets/77454392/2ea08035-15e4-4078-8df9-80847af60682">

**Comment by xXuHaiyang** [comment]
@mdswyz Hi, I didn't make any modification to the training code and ran the code with `mr=0.3, dataset_name='mosi', seeds=[1111, 1112, 1113, 1114, 1115]`, but I got following result
<img width="760" alt="image" src="https://github.com/mdswyz/IMDer/assets/77454392/0e020936-1efc-45da-abf1-1c81cf830abf">
which has a large gap from the number reported in the paper. 
Could you please provide a requirement.txt about the full package lists and their corresponding verision? It will greatly help! 

Thanks!

**Comment by mdswyz** [comment]
you can select the better results from all epochs.

**Comment by pwang322** [comment]
> [@mdswyz](https://github.com/mdswyz) Hi, I didn't make any modification to the training code and ran the code with `mr=0.3, dataset_name='mosi', seeds=[1111, 1112, 1113, 1114, 1115]`, but I got following result <img alt="image" width="760" src="https://private-user-images.githubusercontent.com/77454392/313491304-0e020936-1efc-45da-abf1-1c81cf830abf.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTczOTUwODcsIm5iZiI6MTc1NzM5NDc4NywicGF0aCI6Ii83NzQ1NDM5Mi8zMTM0OTEzMDQtMGUwMjA5MzYtMWVmYy00NWRhLWFiZjEtMWM4MWNmODMwYWJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwOTA5VDA1MTMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhM2IyODk0NjU2Mzc2OGRhMTVhNWExOWJhZjg0NmQ0Zjc2ZTIxZDRhOTM0MjE5ZjQxMjdkNWRjMzM0ODczZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.spkAvV4ouGHVhVvWOLIKWpAYFm5pPkf_Ylpw8DY5GzI"> which has a large gap from the number reported in the paper. Could you please provide a requirement.txt about the full package lists and their corresponding verision? It will greatly help!
> 
> Thanks!

Hi, I also encountered the same issue. Did you solve this problem and obtain results close to those reported in this paper?

Thanks.

**Comment by pwang322** [comment]
> OK, maybe mr=0.0 should also be take into consideration in all the following missing strategy settings:
> 
> [IMDer/trains/singleTask/IMDER.py](https://github.com/mdswyz/IMDer/blob/1901a92f0c91017ef9ac0dc2f2ca0b101a4dec9c/trains/singleTask/IMDER.py#L64)
> 
> Line 64 in [1901a92](/mdswyz/IMDer/commit/1901a92f0c91017ef9ac0dc2f2ca0b101a4dec9c)
> 
>  miss_2 = [0.1, 0.2, 0.3, 0.5, 0.7, 0.9, 1.0] 
> [IMDer/trains/singleTask/IMDER.py](https://github.com/mdswyz/IMDer/blob/1901a92f0c91017ef9ac0dc2f2ca0b101a4dec9c/trains/singleTask/IMDER.py#L65)
> 
> Line 65 in [1901a92](/mdswyz/IMDer/commit/1901a92f0c91017ef9ac0dc2f2ca0b101a4dec9c)
> 
>  miss_1 = [0.1, 0.2, 0.3, 0.2, 0.1, 0.0, 0.0] 
> Otherwise `miss_2[int(self.args.mr*10-1)]` will be -1, which is the last element in the list.

@xXuHaiyang Hi, haiyang, did you succeed in reproducing the results similar to those reported in the paper? How do you make it?
