### ISSUE TITLE
关于模型结果选取的问题

### ISSUE THREAD

**Issue by hustcselwb** [mdswyz/IMDer#3]
请问作者，对于模型的最终结果比如，F1分数，acc2这些指标，你是选择来自不同epoch中的最优结果还是说你论文中的所有数据都来自一个epoch下。期待您的回答，感谢

**Comment by mdswyz** [comment]
您好，模型的最终结果来自一个epoch下，我们会在多次训练中选取5个结果取平均. 当然，如果你要选取不同结果（该领域没有统一标准），我认为最少保证F1和ACC2来自一个，因为他们都只评价二分类。
