### ISSUE TITLE
Why Before running missing cases, you should download the weights pretrained by complete multimodal data

### ISSUE THREAD

**Issue by wupeng1989** [mdswyz/IMDer#5]
Thank you very much for your work. Can you please tell me, (1) why do you want to use the the weights pretrained by complete multimodal data, Is this necessary? (2) if train own dataset and want to use your model, do I also have to have to train the full multimodal pre-training weights ？(3) I didn't find anything related to pre-training using full multimodal in your paper 
 
Very much looking forward to your reply！ @mdswyz

**Comment by mdswyz** [comment]
Pretrained by complete multimodal data is necessary. This is based on the common sense that if we want to estimate the distribution of the data, then it is objectively not changing with the training process. Therefore, we should pretrain a model with complete multimodal data, and the pretrained model is frozen in training incomplete settings.
